export const EVENT_TYPE_MNEMOCODE_FURNITURE = "furniture_display";
export const EVENT_TYPE_MNEMOCODE_CHILDREN_MATINEE = "children_matinee"

export const EVENT_TYPE_MNEMOCODE_LIST = [
  EVENT_TYPE_MNEMOCODE_FURNITURE,
  EVENT_TYPE_MNEMOCODE_CHILDREN_MATINEE
];
